# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
    steps:
      - name: Colnacion repo
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - name: instaling dependecis
     run: npm install
    - name: Generar coverage
     run: npm run coverage

     - name: Coverral git hub
     uses: coverallsapp/github-action@main
     with:
      github-token: ${{ secret.GITHUB_TOKEN }}

